/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;

/**
 *
 * @author AD
 */
public class ManHinhPhanQuyen extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhPhanQuyen
     */
    public ManHinhPhanQuyen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HienThi = new javax.swing.JPanel();
        btn_QuanLy = new javax.swing.JButton();
        btn_ThuNgan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_PhaChe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HienThi.setBackground(new java.awt.Color(255, 255, 255));

        btn_QuanLy.setText("Quản lý");
        btn_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyActionPerformed(evt);
            }
        });

        btn_ThuNgan.setText("Nhân viên thu ngân");
        btn_ThuNgan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThuNganActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Chào mừng bạn đã sẵn sàng bán mình cho tư bản:>");

        btn_PhaChe.setText("Nhân viên pha chế");
        btn_PhaChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhaCheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HienThiLayout = new javax.swing.GroupLayout(HienThi);
        HienThi.setLayout(HienThiLayout);
        HienThiLayout.setHorizontalGroup(
            HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(HienThiLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addGroup(HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_PhaChe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThuNgan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HienThiLayout.setVerticalGroup(
            HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HienThiLayout.createSequentialGroup()
                .addGroup(HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HienThiLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btn_QuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addComponent(btn_ThuNgan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_PhaChe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyActionPerformed
        QuanLy nd = new QuanLy();
        nd.setSize(800, 600);
        nd.setLocation(0, 0);
        HienThi.removeAll();
        HienThi.add(nd, BorderLayout.CENTER);
        HienThi.revalidate();
        HienThi.repaint();  
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QuanLyActionPerformed

    private void btn_ThuNganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThuNganActionPerformed
        NhanVienThuNgan nvtn = new NhanVienThuNgan();
        nvtn.setSize(800, 600);
        nvtn.setLocation(0,0);
        HienThi.removeAll();
        HienThi.add(nvtn, BorderLayout.CENTER);
        HienThi.revalidate();
        HienThi.repaint();  // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThuNganActionPerformed

    private void btn_PhaCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhaCheActionPerformed
        
        NhanVienPhaChe nvpc = new NhanVienPhaChe();
        nvpc.setSize(800, 600);
        nvpc.setLocation(0,0);
        HienThi.removeAll();
        HienThi.add(nvpc, BorderLayout.CENTER);
        HienThi.revalidate();
        HienThi.repaint();// TODO add your handling code here:
    }//GEN-LAST:event_btn_PhaCheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhPhanQuyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HienThi;
    public javax.swing.JButton btn_PhaChe;
    public javax.swing.JButton btn_QuanLy;
    public javax.swing.JButton btn_ThuNgan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
